Repository bitcamp-wasd/secret-back, pull requests merged in 2024-06, with the labels that each got.

#2 config init
  config/.gitignore
  config/build.gradle
  config/gradle/wrapper/gradle-wrapper.jar
  config/gradle/wrapper/gradle-wrapper.properties
  config/gradlew
  config/gradlew.bat
  config/settings.gradle
  config/src/main/java/com/example/config/ConfigApplication.java
  config/src/main/resources/application.properties
  config/src/test/java/com/example/config/ConfigApplicationTests.java
Labels: 🏗️Config

#3 config init
  gateway/.gitignore
  gateway/build.gradle
  gateway/gradle/wrapper/gradle-wrapper.jar
  gateway/gradle/wrapper/gradle-wrapper.properties
  gateway/gradlew
  gateway/gradlew.bat
  gateway/settings.gradle
  gateway/src/main/java/com/example/gateway/GatewayApplication.java
  gateway/src/main/resources/application.properties
  gateway/src/test/java/com/example/gateway/GatewayApplicationTests.java
Labels: 🏗️Config

#4 eureka delete
  config/src/main/resources/application.properties
  eureka/.gitignore
  eureka/build.gradle
  eureka/gradle/wrapper/gradle-wrapper.jar
  eureka/gradle/wrapper/gradle-wrapper.properties
  eureka/gradlew
  eureka/gradlew.bat
  eureka/settings.gradle
  eureka/src/main/java/com/example/eureka/EurekaApplication.java
  eureka/src/main/resources/application.properties
  eureka/src/test/java/com/example/eureka/EurekaApplicationTests.java
Labels: 🏗️Config

#5 eureka init
  eureka/.gitignore
  eureka/build.gradle
  eureka/gradle/wrapper/gradle-wrapper.jar
  eureka/gradle/wrapper/gradle-wrapper.properties
  eureka/gradlew
  eureka/gradlew.bat
  eureka/settings.gradle
  eureka/src/main/java/com/example/eureka/EurekaApplication.java
  eureka/src/main/resources/application.properties
  eureka/src/test/java/com/example/eureka/EurekaApplicationTests.java
Labels: 🏗️Config

#7 MSA Config (eureka, config)
  config/.gitignore
  config/build.gradle
  config/src/main/java/com/example/config/ConfigApplication.java
  config/src/main/resources/application.properties
  config/src/main/resources/application.yml
  eureka/src/main/resources/application.properties
  eureka/src/main/resources/application.yml
  gateway/build.gradle
  gateway/src/main/java/com/example/gateway/GatewayApplication.java
  gateway/src/main/resources/application.properties
  gateway/src/main/resources/application.yml
Labels: 🏗️Config

#9 로그인 회원가입 구현
  user/build.gradle
  user/src/main/java/com/example/user/common/CertificationNumber.java
  user/src/main/java/com/example/user/common/ResponseCode.java
  user/src/main/java/com/example/user/common/ResponseMessage.java
  user/src/main/java/com/example/user/component/AuthEntryPoint.java
  user/src/main/java/com/example/user/component/CustomAccessDeniedHandler.java
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/component/ValidationExceptionHandler.java
  user/src/main/java/com/example/user/config/RedisConfig.java
  user/src/main/java/com/example/user/config/WebSecurityConfig.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/request/auth/CheckCertificationRequestDto.java
  user/src/main/java/com/example/user/dto/request/auth/EmailCertificationRequestDto.java
  user/src/main/java/com/example/user/dto/request/auth/NickNameCheckRequestDto.java
  user/src/main/java/com/example/user/dto/request/auth/SignInRequestDto.java
  user/src/main/java/com/example/user/dto/request/auth/SignUpRequestDto.java
  user/src/main/java/com/example/user/dto/response/ResponseDto.java
  user/src/main/java/com/example/user/dto/response/auth/CheckCertificationResponseDto.java
  user/src/main/java/com/example/user/dto/response/auth/EmailCertificationResponseDto.java
  user/src/main/java/com/example/user/dto/response/auth/NickNameCheckResponseDto.java
  user/src/main/java/com/example/user/dto/response/auth/SignInResponseDto.java
  user/src/main/java/com/example/user/dto/response/auth/SignUpResponseDto.java
  user/src/main/java/com/example/user/entity/CustomOAuth2User.java
  user/src/main/java/com/example/user/entity/UserEntity.java
  user/src/main/java/com/example/user/entity/UserRankEntity.java
  user/src/main/java/com/example/user/entity/UserRecordEntity.java
  user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/example/user/filter/TokenUtils.java
  user/src/main/java/com/example/user/provider/EmailProvider.java
  user/src/main/java/com/example/user/provider/JwtProvider.java
  user/src/main/java/com/example/user/repository/UserRepository.java
  user/src/main/java/com/example/user/service/AuthService.java
  user/src/main/java/com/example/user/service/RedisService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
  user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
  user/src/main/resources/application.properties
Labels: ✨ FEAT, 🏗️Config

#10 게이트웨어 설정 변경, 비디오 서비스 엔티티 생성
  gateway/src/main/java/com/example/gateway/GatewayApplication.java
  gateway/src/main/resources/application.yml
  video/build.gradle
  video/src/main/java/com/example/video/config/S3ClientConfig.java
  video/src/main/java/com/example/video/controller/TestController.java
  video/src/main/java/com/example/video/controller/UploadController.java
  video/src/main/java/com/example/video/dto/VideoRegisterDto.java
  video/src/main/java/com/example/video/entity/Category.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/entity/PostComment.java
  video/src/main/java/com/example/video/entity/PostLikeList.java
  video/src/main/java/com/example/video/entity/SheetMusic.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/entity/state/VideoState.java
  video/src/main/java/com/example/video/repository/CategoryRepository.java
  video/src/main/java/com/example/video/repository/PostCommentRepository.java
  video/src/main/java/com/example/video/repository/PostLikeListRepository.java
  video/src/main/java/com/example/video/repository/PostRepository.java
  video/src/main/java/com/example/video/repository/VideoRepository.java
  video/src/main/java/com/example/video/service/UploadService.java
  video/src/main/java/com/example/video/util/Util.java
  video/src/main/resources/application.yml
  video/src/test/java/com/example/video/config/S3ClientConfigTest.java
Labels: ✨ FEAT, 🏗️Config

#11 Feat/video
  gateway/src/main/resources/application.yml
  video/src/main/java/com/example/video/VideoApplication.java
  video/src/main/java/com/example/video/api/UserRestApi.java
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/controller/UploadController.java
  video/src/main/java/com/example/video/dto/VideoRegisterDto.java
  video/src/main/java/com/example/video/dto/post/PostRegisterDto.java
  video/src/main/java/com/example/video/dto/post/PostResponseDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/entity/SheetMusic.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/global/config/S3ClientConfig.java
  video/src/main/java/com/example/video/global/util/Util.java
  video/src/main/java/com/example/video/repository/CategoryRepository.java
  video/src/main/java/com/example/video/repository/SheetMusicRepository.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/java/com/example/video/service/UploadService.java
  video/src/main/java/com/example/video/util/Util.java
Labels: ✨ FEAT

#12 마이페이지 랭크 포인트 구현
  user/src/main/java/com/example/user/entity/UserEntity.java
  user/src/main/java/com/example/user/entity/UserRankEntity.java
  user/src/main/java/com/example/user/repository/UserRankRepository.java
  user/src/main/java/com/example/user/repository/UserRepository.java
  user/src/main/java/com/example/user/service/UserService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
  user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
  user/src/main/resources/application.yml
Labels: ✨ FEAT

#13 마이페이지 내정보 보여주기 수정하기 구현
  user/src/main/java/com/example/user/config/WebSecurityConfig.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/UpdateUserInfoDto.java
  user/src/main/java/com/example/user/dto/UserInfoDto.java
  user/src/main/java/com/example/user/entity/UserEntity.java
  user/src/main/java/com/example/user/service/UserService.java
  user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
Labels: 🛠FIX, ✨ FEAT

#15 email -> userId + role 레디스에 담기 + email 검증 -> userId변환
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/entity/CustomOAuth2User.java
  user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/example/user/provider/JwtProvider.java
  user/src/main/java/com/example/user/service/UserService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
Labels: 🛠FIX

#16 userEntity -> oAuth2User 버그 픽스
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/entity/CustomOAuth2User.java
  user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/example/user/provider/JwtProvider.java
  user/src/main/java/com/example/user/service/UserService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
  user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
Labels: 🛠FIX

#19 key accessToken value userId,role 담기
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/example/user/filter/TokenUtils.java
  user/src/main/java/com/example/user/service/RedisService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
Labels: 🛠FIX
