Repository bitcamp-wasd/secret-back, pull requests merged in 2024-07, with the labels that each got.

#20 gateway, user 프로젝트 redis 설정 변경
  gateway/src/main/java/com/example/gateway/config/RedisConfig.java
  gateway/src/main/java/com/example/gateway/filter/LoginFilter.java
  gateway/src/main/java/com/example/gateway/util/JwtUtil.java
  user/src/main/java/com/example/user/config/RedisConfig.java
  user/src/main/java/com/example/user/service/RedisService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
Labels: 🛠FIX

#21 battle project config
  battle/.gitignore
  battle/build.gradle
  battle/gradle/wrapper/gradle-wrapper.jar
  battle/gradle/wrapper/gradle-wrapper.properties
  battle/gradlew
  battle/gradlew.bat
  battle/settings.gradle
  battle/src/main/java/com/example/battle/BattleApplication.java
  battle/src/main/resources/application.properties
  battle/src/test/java/com/example/battle/BattleApplicationTests.java
Labels: 🏗️Config

#22 challegeConfig
  challenge/.eslintrc.js
  challenge/.gitignore
  challenge/.prettierrc
  challenge/README.md
  challenge/nest-cli.json
  challenge/package.json
  challenge/src/app.controller.spec.ts
  challenge/src/app.controller.ts
  challenge/src/app.module.ts
  challenge/src/app.service.ts
  challenge/src/main.ts
  challenge/test/app.e2e-spec.ts
  challenge/test/jest-e2e.json
  challenge/tsconfig.build.json
  challenge/tsconfig.json
  challenge/yarn.lock
Labels: 🏗️Config

#23 redis nickname 담기 oauth2 리다이렉트 수정
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/config/WebSecurityConfig.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/entity/CustomOAuth2User.java
  user/src/main/java/com/example/user/filter/JwtAuthenticationFilter.java
  user/src/main/java/com/example/user/provider/JwtProvider.java
  user/src/main/java/com/example/user/service/RedisService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
  user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
Labels: 🛠FIX

#25 로그인 헤더 base64 인코딩 후 디코딩(헤더에 한글 깨짐 문제 해결)
  gateway/src/main/java/com/example/gateway/config/RedisConfig.java
  gateway/src/main/java/com/example/gateway/filter/LoginFilter.java
  user/src/main/java/com/example/user/config/RedisConfig.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/service/RedisService.java
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/controller/TestController.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/global/annotation/HeaderUserAuthArgumentResolver.java
  video/src/main/java/com/example/video/global/config/Base64Config.java
  video/src/main/java/com/example/video/global/config/annotationConfig.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/resources/application.yml
Labels: ✨ FEAT

#27 동영상 좋아요 기능
  user/src/main/java/com/example/user/annotation/HeaderUserAuth.java
  user/src/main/java/com/example/user/annotation/HeaderUserAuthArgumentResolver.java
  user/src/main/java/com/example/user/config/Base64Config.java
  user/src/main/java/com/example/user/config/annotationConfig.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/UserAuth.java
  video/src/main/java/com/example/video/controller/PostCommentController.java
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/controller/PostLikeController.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/entity/VideoLikeList.java
  video/src/main/java/com/example/video/repository/PostLikeListRepository.java
  video/src/main/java/com/example/video/repository/VideoLikeListRepository.java
  video/src/main/java/com/example/video/service/PostLikeService.java
Labels: ✨ FEAT

#26 logout -> sign-out 변경
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/service/implement/OAuth2UserServiceImpl.java
Labels: 🛠FIX

#28 update 수정 + 예외처리 추가
  user/src/main/java/com/example/user/common/ParseUtil.java
  user/src/main/java/com/example/user/component/DuplicateException.java
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/component/PasswordFormatException.java
  user/src/main/java/com/example/user/component/ValidationExceptionHandler.java
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/UserInfoDto.java
  user/src/main/java/com/example/user/dto/info/UpdateUserInfoDto.java
  user/src/main/java/com/example/user/dto/info/UserAuth.java
  user/src/main/java/com/example/user/dto/info/UserInfoDto.java
  user/src/main/java/com/example/user/service/UserService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
Labels: 🛠FIX

#30 Update application.yml
  user/src/main/resources/application.yml
Labels: 🛠FIX, 🚀deploy

#31 Update application.yml
  gateway/src/main/resources/application.yml
Labels: 🛠FIX, 🚀deploy

#32 user Dockerfile 설정
  user/dockerfile
Labels: 🏗️Config

#33 deploy
  user/dockerfile
Labels: 🚀deploy

#34 Dockerfile config
  battle/dockerfile
  gateway/dockerfile
  video/dockerfile
Labels: 🏗️Config

#35 Dev
  battle/dockerfile
  gateway/dockerfile
  video/dockerfile
Labels: 🚀deploy

#36 Update application.yml
  video/src/main/resources/application.yml
Labels: 🚀deploy

#37 Post 검색 및 자잘한 기능 구현
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/controller/VideoController.java
  video/src/main/java/com/example/video/controller/VideoLikeController.java
  video/src/main/java/com/example/video/dto/post/request/PostRegisterDto.java
  video/src/main/java/com/example/video/dto/post/response/MyPostDto.java
  video/src/main/java/com/example/video/dto/post/response/PostRegisterResponseDto.java
  video/src/main/java/com/example/video/dto/post/response/PostResponseDto.java
  video/src/main/java/com/example/video/dto/post/response/VideoResponseDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/repository/PostRepository.java
  video/src/main/java/com/example/video/repository/VideoLikeListRepository.java
  video/src/main/java/com/example/video/repository/VideoRepository.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/java/com/example/video/service/VideoLikeService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT

#38 Dev
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/controller/VideoController.java
  video/src/main/java/com/example/video/controller/VideoLikeController.java
  video/src/main/java/com/example/video/dto/post/request/PostRegisterDto.java
  video/src/main/java/com/example/video/dto/post/response/MyPostDto.java
  video/src/main/java/com/example/video/dto/post/response/PostRegisterResponseDto.java
  video/src/main/java/com/example/video/dto/post/response/PostResponseDto.java
  video/src/main/java/com/example/video/dto/post/response/VideoResponseDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/repository/PostRepository.java
  video/src/main/java/com/example/video/repository/VideoLikeListRepository.java
  video/src/main/java/com/example/video/repository/VideoRepository.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/java/com/example/video/service/VideoLikeService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: 🚀deploy

#39 Update OAuth2SuccessHandler.java
  user/src/main/java/com/example/user/component/OAuth2SuccessHandler.java
Labels: 🛠FIX, 🚀deploy

#40 배틀 진행중 + 유저 닉네임 랭크네임 정보 보내기
  battle/build.gradle
  battle/src/main/java/com/example/battle/entity/Battle.java
  battle/src/main/java/com/example/battle/entity/BattleComment.java
  battle/src/main/java/com/example/battle/entity/BattleVoteList.java
  battle/src/main/resources/application.properties
  battle/src/main/resources/application.yml
  battle/src/main/resources/mapper/battleMapper.xml
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/info/UserApiInfo.java
  user/src/main/java/com/example/user/service/UserService.java
Labels: ✨ FEAT

#41 Post 기능 자잘한 것들
  video/build.gradle
  video/src/main/java/com/example/video/api/UserRestApi.java
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/controller/TestController.java
  video/src/main/java/com/example/video/controller/VideoController.java
  video/src/main/java/com/example/video/dto/post/request/PostListDto.java
  video/src/main/java/com/example/video/dto/post/response/VideoResponseDto.java
  video/src/main/java/com/example/video/dto/user/response/UserInfoDto.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT

#42 Post 기능 상세 페이지 조회
  user/src/main/java/com/example/user/dto/info/UserApiInfo.java
  user/src/main/java/com/example/user/dto/info/UserInfoDto.java
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/dto/post/response/PostResponseDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/repository/PostRepository.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT

#43 Post 기능 상세 페이지 조회 및 전체 페이지 조회 필터링
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/controller/TestController.java
  video/src/main/java/com/example/video/dto/post/response/PostResponseDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/repository/PostRepository.java
  video/src/main/java/com/example/video/repository/VideoRepository.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT

#44 Post 기능 상세 페이지 조회 필터링 기능 일부 수정
  video/src/main/java/com/example/video/repository/PostRepository.java
Labels: 🛠FIX

#45 동영상 좋아요 기능 추가
  video/src/main/java/com/example/video/controller/VideoLikeController.java
  video/src/main/java/com/example/video/service/VideoLikeService.java
Labels: ✨ FEAT

#46 게시물 검색 기능 구현
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/dto/post/request/PostSortDto.java
  video/src/main/java/com/example/video/repository/PostRepository.java
  video/src/main/java/com/example/video/service/PostService.java
Labels: ✨ FEAT

#47 배틀 상세보기 투표 댓글 댓글 페이지네이션
  battle/build.gradle
  battle/src/main/java/com/example/battle/config/MyBatisConfig.java
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/BattleDto.java
  battle/src/main/java/com/example/battle/dto/CommentDto.java
  battle/src/main/java/com/example/battle/dto/info/PostDto.java
  battle/src/main/java/com/example/battle/dto/info/UserDto.java
  battle/src/main/java/com/example/battle/entity/Battle.java
  battle/src/main/java/com/example/battle/entity/BattleComment.java
  battle/src/main/java/com/example/battle/entity/BattleVoteList.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/java/com/example/battle/service/BattleService.java
  battle/src/main/java/com/example/battle/service/BattleVoteService.java
  battle/src/main/resources/application.yml
  battle/src/main/resources/mapper/battleMapper.xml
Labels: ✨ FEAT

#48 게시물 ID로 비디오 조회(서버간 통신용)
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/dto/post/response/VideoApiDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/repository/PostRepository.java
  video/src/main/java/com/example/video/service/PostService.java
Labels: ✨ FEAT

#49 Dev fix user battle
  battle/build.gradle
  battle/src/main/java/com/example/battle/BattleApplication.java
  battle/src/main/java/com/example/battle/annotation/HeaderUserAuth.java
  battle/src/main/java/com/example/battle/annotation/HeaderUserAuthArgumentResolver.java
  battle/src/main/java/com/example/battle/api/UserRestApi.java
  battle/src/main/java/com/example/battle/api/VideoRestApi.java
  battle/src/main/java/com/example/battle/config/Base64Config.java
  battle/src/main/java/com/example/battle/config/annotationConfig.java
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/BattleDto.java
  battle/src/main/java/com/example/battle/dto/auth/UserAuth.java
  battle/src/main/java/com/example/battle/dto/info/PostDto.java
  battle/src/main/java/com/example/battle/dto/post/response/PostInfoDto.java
  battle/src/main/java/com/example/battle/dto/user/response/UserRankInfoDto.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/java/com/example/battle/service/BattleService.java
  battle/src/main/java/com/example/battle/util/ParseUtil.java
  battle/src/main/resources/application.yml
  user/src/main/java/com/example/user/common/ResponseCode.java
  user/src/main/java/com/example/user/common/ResponseMessage.java
  user/src/main/java/com/example/user/common/ValidationUtil.java
  user/src/main/java/com/example/user/component/Exception/DuplicateException.java
  user/src/main/java/com/example/user/component/Exception/NicknameFormatException.java
  user/src/main/java/com/example/user/component/Exception/PasswordFormatException.java
  user/src/main/java/com/example/user/component/Exception/ValidationExceptionHandler.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/info/UserRankInfo.java
  user/src/main/java/com/example/user/dto/response/auth/NickNameCheckResponseDto.java
  user/src/main/java/com/example/user/service/UserService.java
  user/src/main/java/com/example/user/service/implement/AuthServiceImpl.java
Labels: 🛠FIX

#50 배틀 연결 방식 수정
  battle/src/main/java/com/example/battle/annotation/HeaderUserAuthArgumentResolver.java
  battle/src/main/java/com/example/battle/api/VideoRestApi.java
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleService.java
  battle/src/main/resources/mapper/battleMapper.xml
Labels: ✨ FEAT

#51 challenge 설정
  challenge/package.json
  challenge/src/app.module.ts
  challenge/src/auth/headers.decorator.ts
  challenge/src/auth/userAuth.dto.ts
  challenge/src/challenge/challenge.collection.ts
  challenge/src/challenge/challenge.controller.ts
  challenge/src/challenge/challenge.module.ts
  challenge/src/challenge/challenge.service.ts
  challenge/src/challenge/state.enum.ts
  challenge/src/challengeList/challengeList.collection.ts
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.service.ts
  challenge/src/comment/comment.collection.ts
  challenge/src/comment/comment.controller.ts
  challenge/src/comment/comment.service.ts
  challenge/src/config/cloud.config.ts
  challenge/src/config/cloud.provider.ts
  challenge/src/config/eureka.config.ts
  challenge/src/main.ts
  challenge/src/module/config.module.ts
  challenge/src/module/mongo.module.ts
  challenge/src/vote/vote.collection.ts
  challenge/src/vote/vote.controller.ts
  challenge/src/vote/vote.repository.ts
  challenge/src/vote/vote.service.ts
  challenge/yarn.lock
Labels: 🏗️Config

#52 VideoId값으로 PostId 값 가져오기
  video/src/main/java/com/example/video/controller/VideoController.java
  video/src/main/java/com/example/video/dto/post/response/PostIdDto.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT

#53 배틀 등록 투표 확인 체크 기능 추가
  battle/src/main/java/com/example/battle/api/VideoRestApi.java
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/BattleRegisterDto.java
  battle/src/main/java/com/example/battle/dto/post/response/PostIdDto.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/java/com/example/battle/service/BattleService.java
  battle/src/main/java/com/example/battle/service/BattleVoteService.java
  battle/src/main/resources/mapper/battleMapper.xml
Labels: ✨ FEAT

#54 Video 상세 보기 Video파일 이름 가져오기 추가
  video/src/main/java/com/example/video/controller/VideoController.java
  video/src/main/java/com/example/video/dto/post/response/VideoResponseDto.java
  video/src/main/java/com/example/video/entity/Video.java
Labels: 🛠FIX

#55 날짜 localDate -> localDateTime 수정
  battle/src/main/java/com/example/battle/dto/BattleDto.java
  battle/src/main/java/com/example/battle/dto/CommentDto.java
  battle/src/main/java/com/example/battle/entity/Battle.java
  battle/src/main/java/com/example/battle/entity/BattleComment.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/java/com/example/battle/service/BattleService.java
  battle/src/main/resources/mapper/battleMapper.xml
Labels: 🛠FIX

#56 Video postId로 게시물 userId 조회
  video/src/main/java/com/example/video/controller/PostController.java
  video/src/main/java/com/example/video/dto/post/response/UserInfoDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/service/PostService.java
Labels: ✨ FEAT

#57 배틀 종료시 포인트 적용 및 상태 종료 변경
  battle/src/main/java/com/example/battle/BattleApplication.java
  battle/src/main/java/com/example/battle/api/UserRestApi.java
  battle/src/main/java/com/example/battle/api/VideoRestApi.java
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/post/response/PostUserIdDto.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleService.java
  battle/src/main/resources/mapper/battleMapper.xml
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/service/UserService.java
Labels: ✨ FEAT

#59 배틀 게시판 삭제 위한 dto 추가
  battle/src/main/java/com/example/battle/dto/BattleDto.java
  battle/src/main/java/com/example/battle/service/BattleService.java
Labels: 🛠FIX

#60 Dev
  battle/src/main/java/com/example/battle/dto/BattleDto.java
  battle/src/main/java/com/example/battle/service/BattleService.java
Labels: 🚀deploy

#61 Update application.yml
  battle/src/main/resources/application.yml
Labels: 🚀deploy

#62 마이페이지 댓글 리스트 및 삭제
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/response/BattleMyCommentDto.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/resources/mapper/battleMapper.xml
  user/build.gradle
  user/src/main/java/com/example/user/UserApplication.java
  user/src/main/java/com/example/user/api/BattleRestApi.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/battle/response/BattleMyCommentDto.java
  user/src/main/java/com/example/user/service/UserService.java
Labels: ✨ FEAT

#63 Dev
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/response/BattleMyCommentDto.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/resources/mapper/battleMapper.xml
  user/build.gradle
  user/src/main/java/com/example/user/UserApplication.java
  user/src/main/java/com/example/user/api/BattleRestApi.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/battle/response/BattleMyCommentDto.java
  user/src/main/java/com/example/user/service/UserService.java
Labels: 🚀deploy

#64 챌린지 동영상 업로드, 관리자 챌린지 생성, 챌린지 투표 기능, ...
  challenge/package.json
  challenge/src/app.controller.spec.ts
  challenge/src/app.controller.ts
  challenge/src/app.module.ts
  challenge/src/app.service.ts
  challenge/src/auth/headers.decorator.ts
  challenge/src/auth/userAuth.dto.ts
  challenge/src/aws/s3.module.ts
  challenge/src/aws/s3.service.ts
  challenge/src/challenge/challenge.collection.ts
  challenge/src/challenge/challenge.controller.ts
  challenge/src/challenge/challenge.module.ts
  challenge/src/challenge/challenge.service.ts
  challenge/src/challenge/dto/request/new-challenge.dto.ts
  challenge/src/challenge/state.enum.ts
  challenge/src/challengeList/challengeList.collection.ts
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.module.ts
  challenge/src/challengeList/challengeList.service.ts
  challenge/src/challengeList/dto/request/challenge-upload.dto.ts
  challenge/src/challengeList/dto/response/challenge-upload-res.dto.ts
  challenge/src/config/cloud.config.ts
  challenge/src/config/cloud.provider.ts
  challenge/src/module/mongo.module.ts
  challenge/src/schedule/task.module.ts
  challenge/src/schedule/task.service.ts
  challenge/src/vote/dto/request/voteRequest.dto.ts
  challenge/src/vote/vote.collection.ts
  challenge/src/vote/vote.controller.ts
  challenge/src/vote/vote.module.ts
  challenge/src/vote/vote.repository.ts
  challenge/src/vote/vote.service.ts
  challenge/yarn.lock
  video/src/main/java/com/example/video/controller/PostCommentController.java
  video/src/main/java/com/example/video/controller/VideoLikeController.java
  video/src/main/java/com/example/video/dto/comment/request/InsertCommentRequestDto.java
  video/src/main/java/com/example/video/entity/PostComment.java
  video/src/main/java/com/example/video/repository/VideoLikeListRepository.java
  video/src/main/java/com/example/video/service/PostCommentService.java
  video/src/main/java/com/example/video/service/VideoLikeService.java
Labels: ✨ FEAT

#65 유저 아이디 리스트 입력시 해당 정보리스트 출력
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/info/request/UserIdRequestDto.java
  user/src/main/java/com/example/user/dto/info/response/UserApiInfo.java
  user/src/main/java/com/example/user/dto/info/response/UserListDto.java
  user/src/main/java/com/example/user/dto/info/response/UserRankInfo.java
  user/src/main/java/com/example/user/repository/UserRepository.java
  user/src/main/java/com/example/user/service/UserService.java
Labels: 🛠FIX, ✨ FEAT

#66 게시물 삭제 및 업데이트(제목, 설명, 카테고리, 썸네일, 악보) 구현
  video/src/main/java/com/example/video/controller/VideoController.java
  video/src/main/java/com/example/video/controller/VideoLikeController.java
  video/src/main/java/com/example/video/dto/video/request/UpdateRequestDto.java
  video/src/main/java/com/example/video/dto/video/response/UpdateResponseDto.java
  video/src/main/java/com/example/video/dto/video/response/VideoResponseDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/entity/PostComment.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT

#68 Dev
  challenge/dockerfile
  challenge/package.json
  challenge/src/app.controller.spec.ts
  challenge/src/app.controller.ts
  challenge/src/app.module.ts
  challenge/src/app.service.ts
  challenge/src/auth/headers.decorator.ts
  challenge/src/auth/userAuth.dto.ts
  challenge/src/aws/s3.module.ts
  challenge/src/aws/s3.service.ts
  challenge/src/challenge/challenge.collection.ts
  challenge/src/challenge/challenge.controller.ts
  challenge/src/challenge/challenge.module.ts
  challenge/src/challenge/challenge.service.ts
  challenge/src/challenge/dto/request/new-challenge.dto.ts
  challenge/src/challenge/state.enum.ts
  challenge/src/challengeList/challengeList.collection.ts
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.module.ts
  challenge/src/challengeList/challengeList.service.ts
  challenge/src/challengeList/dto/request/challenge-upload.dto.ts
  challenge/src/challengeList/dto/response/challenge-upload-res.dto.ts
  challenge/src/config/cloud.config.ts
  challenge/src/config/cloud.provider.ts
  challenge/src/module/mongo.module.ts
  challenge/src/schedule/task.module.ts
  challenge/src/schedule/task.service.ts
  challenge/src/vote/dto/request/voteRequest.dto.ts
  challenge/src/vote/vote.collection.ts
  challenge/src/vote/vote.controller.ts
  challenge/src/vote/vote.module.ts
  challenge/src/vote/vote.repository.ts
  challenge/src/vote/vote.service.ts
  challenge/yarn.lock
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/info/request/UserIdRequestDto.java
  user/src/main/java/com/example/user/dto/info/response/UserApiInfo.java
  user/src/main/java/com/example/user/dto/info/response/UserListDto.java
  user/src/main/java/com/example/user/dto/info/response/UserRankInfo.java
  user/src/main/java/com/example/user/repository/UserRepository.java
  user/src/main/java/com/example/user/service/UserService.java
  video/src/main/java/com/example/video/controller/PostCommentController.java
  video/src/main/java/com/example/video/controller/VideoController.java
  video/src/main/java/com/example/video/controller/VideoLikeController.java
  video/src/main/java/com/example/video/dto/comment/request/InsertCommentRequestDto.java
  video/src/main/java/com/example/video/dto/video/request/UpdateRequestDto.java
  video/src/main/java/com/example/video/dto/video/response/UpdateResponseDto.java
  video/src/main/java/com/example/video/dto/video/response/VideoResponseDto.java
  video/src/main/java/com/example/video/entity/Post.java
  video/src/main/java/com/example/video/entity/PostComment.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/repository/VideoLikeListRepository.java
  video/src/main/java/com/example/video/service/PostCommentService.java
  video/src/main/java/com/example/video/service/PostService.java
  video/src/main/java/com/example/video/service/VideoLikeService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT, 🚀deploy

#69 유저 api rankname 추가 및 rankimage ->rankname 변경
  battle/src/main/java/com/example/battle/api/UserRestApi.java
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/response/BattleMyCommentDto.java
  battle/src/main/java/com/example/battle/dto/user/response/UserApiInfoDto.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/resources/mapper/battleMapper.xml
  user/src/main/java/com/example/user/api/BattleRestApi.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/battle/response/BattleMyCommentDto.java
  user/src/main/java/com/example/user/dto/info/response/UserListDto.java
  user/src/main/java/com/example/user/service/UserService.java
Labels: 🛠FIX

#70 마이페이지 배틀댓글 리스트 선택삭제 수정
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/CommentDto.java
  battle/src/main/java/com/example/battle/dto/battle/request/BattleCommentListDto.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/resources/mapper/battleMapper.xml
  user/src/main/java/com/example/user/repository/UserRepository.java
Labels: 🛠FIX

#71 동영상 댓글 기능
  video/src/main/java/com/example/video/api/UserRestApi.java
  video/src/main/java/com/example/video/controller/PostCommentController.java
  video/src/main/java/com/example/video/controller/TestController.java
  video/src/main/java/com/example/video/dto/comment/request/DeleteCommentRequestDto.java
  video/src/main/java/com/example/video/dto/comment/request/UpdateCommentDto.java
  video/src/main/java/com/example/video/dto/comment/request/UserRequestDto.java
  video/src/main/java/com/example/video/dto/comment/response/CommentResponseDto.java
  video/src/main/java/com/example/video/dto/comment/response/MyCommentResponseDto.java
  video/src/main/java/com/example/video/dto/comment/response/UserResponseDto.java
  video/src/main/java/com/example/video/entity/PostComment.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/repository/PostCommentRepository.java
  video/src/main/java/com/example/video/service/PostCommentService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: ✨ FEAT

#72 Dev
  battle/src/main/java/com/example/battle/api/UserRestApi.java
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/dto/CommentDto.java
  battle/src/main/java/com/example/battle/dto/battle/request/BattleCommentListDto.java
  battle/src/main/java/com/example/battle/dto/response/BattleMyCommentDto.java
  battle/src/main/java/com/example/battle/dto/user/response/UserApiInfoDto.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleCommentService.java
  battle/src/main/resources/mapper/battleMapper.xml
  user/src/main/java/com/example/user/api/BattleRestApi.java
  user/src/main/java/com/example/user/controller/UserController.java
  user/src/main/java/com/example/user/dto/battle/response/BattleMyCommentDto.java
  user/src/main/java/com/example/user/dto/info/response/UserListDto.java
  user/src/main/java/com/example/user/repository/UserRepository.java
  user/src/main/java/com/example/user/service/UserService.java
  video/src/main/java/com/example/video/api/UserRestApi.java
  video/src/main/java/com/example/video/controller/PostCommentController.java
  video/src/main/java/com/example/video/controller/TestController.java
  video/src/main/java/com/example/video/dto/comment/request/DeleteCommentRequestDto.java
  video/src/main/java/com/example/video/dto/comment/request/UpdateCommentDto.java
  video/src/main/java/com/example/video/dto/comment/request/UserRequestDto.java
  video/src/main/java/com/example/video/dto/comment/response/CommentResponseDto.java
  video/src/main/java/com/example/video/dto/comment/response/MyCommentResponseDto.java
  video/src/main/java/com/example/video/dto/comment/response/UserResponseDto.java
  video/src/main/java/com/example/video/entity/PostComment.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/repository/PostCommentRepository.java
  video/src/main/java/com/example/video/service/PostCommentService.java
  video/src/main/java/com/example/video/service/VideoService.java
Labels: 🚀deploy

#73 동영상 마이페이지 댓글 기능에 videoId 값 추가
  video/src/main/java/com/example/video/dto/comment/response/MyCommentResponseDto.java
  video/src/main/java/com/example/video/entity/PostComment.java
  video/src/main/java/com/example/video/entity/Video.java
  video/src/main/java/com/example/video/repository/PostCommentRepository.java
  video/src/main/java/com/example/video/service/PostCommentService.java
Labels: 🛠FIX

#74 해당 동영상 게시물 없을 시 배틀 null 업데이트 후 게시글 삭제 예외처리
  battle/src/main/java/com/example/battle/controller/BattleController.java
  battle/src/main/java/com/example/battle/mapper/BattleMapper.java
  battle/src/main/java/com/example/battle/service/BattleService.java
  battle/src/main/resources/mapper/battleMapper.xml
Labels: 🛠FIX

#77 챌린지 투표 및 챌린지 상세 기능 및 api 통신
  challenge/package.json
  challenge/src/app.module.ts
  challenge/src/aws/s3.service.ts
  challenge/src/challenge/challenge.controller.ts
  challenge/src/challenge/challenge.module.ts
  challenge/src/challenge/challenge.service.ts
  challenge/src/challenge/dto/response/challenge-complete-res.dto.ts
  challenge/src/challenge/dto/response/challenge-data-res.dto.ts
  challenge/src/challenge/dto/response/challengeVideo.dto.ts
  challenge/src/challengeList/challengeList.collection.ts
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.module.ts
  challenge/src/challengeList/challengeList.service.ts
  challenge/src/challengeList/dto/request/challenge-upload.dto.ts
  challenge/src/comment/comment.collection.ts
  challenge/src/comment/comment.controller.ts
  challenge/src/comment/comment.module.ts
  challenge/src/comment/comment.service.ts
  challenge/src/comment/dto/request/createComment.request.ts
  challenge/src/comment/dto/request/deleteComment.request.ts
  challenge/src/comment/dto/request/patchComment.request.ts
  challenge/src/comment/dto/response/commentList.response.ts
  challenge/src/comment/dto/response/myComment.response.ts
  challenge/src/config/cloud.provider.ts
  challenge/src/main.ts
  challenge/src/restApi/api.module.ts
  challenge/src/restApi/api.service.ts
  challenge/src/schedule/task.service.ts
  challenge/yarn.lock
Labels: ✨ FEAT

#76 리프레쉬토큰으로 엑세스 재발급 연결
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/filter/TokenUtils.java
  user/src/main/java/com/example/user/service/RedisService.java
Labels: ✨ FEAT

#78 좋아요 확인 기능 추가
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.service.ts
  challenge/src/comment/comment.controller.ts
Labels: ✨ FEAT

#79 Dev
  challenge/package.json
  challenge/src/app.module.ts
  challenge/src/aws/s3.service.ts
  challenge/src/challenge/challenge.controller.ts
  challenge/src/challenge/challenge.module.ts
  challenge/src/challenge/challenge.service.ts
  challenge/src/challenge/dto/response/challenge-complete-res.dto.ts
  challenge/src/challenge/dto/response/challenge-data-res.dto.ts
  challenge/src/challenge/dto/response/challengeVideo.dto.ts
  challenge/src/challengeList/challengeList.collection.ts
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.module.ts
  challenge/src/challengeList/challengeList.service.ts
  challenge/src/challengeList/dto/request/challenge-upload.dto.ts
  challenge/src/comment/comment.collection.ts
  challenge/src/comment/comment.controller.ts
  challenge/src/comment/comment.module.ts
  challenge/src/comment/comment.service.ts
  challenge/src/comment/dto/request/createComment.request.ts
  challenge/src/comment/dto/request/deleteComment.request.ts
  challenge/src/comment/dto/request/patchComment.request.ts
  challenge/src/comment/dto/response/commentList.response.ts
  challenge/src/comment/dto/response/myComment.response.ts
  challenge/src/config/cloud.provider.ts
  challenge/src/main.ts
  challenge/src/restApi/api.module.ts
  challenge/src/restApi/api.service.ts
  challenge/src/schedule/task.service.ts
  challenge/yarn.lock
  user/src/main/java/com/example/user/controller/AuthController.java
  user/src/main/java/com/example/user/filter/TokenUtils.java
  user/src/main/java/com/example/user/service/RedisService.java
Labels: 🚀deploy

#80 나의 챌린지 동영상 기능 추가
  challenge/src/challenge/challenge.service.ts
  challenge/src/challengeList/challengeList.collection.ts
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.service.ts
  video/src/main/java/com/example/video/dto/post/response/MyPostDto.java
  video/src/main/java/com/example/video/entity/Post.java
Labels: ✨ FEAT

#81 Dev
  challenge/src/challenge/challenge.service.ts
  challenge/src/challengeList/challengeList.collection.ts
  challenge/src/challengeList/challengeList.controller.ts
  challenge/src/challengeList/challengeList.service.ts
  video/src/main/java/com/example/video/dto/post/response/MyPostDto.java
  video/src/main/java/com/example/video/entity/Post.java
Labels: 🚀deploy

#82 Update cloud.provider.ts
  challenge/src/config/cloud.provider.ts
Labels: 🚀deploy
